name: test

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            rust:
              - '**.rs'
              - 'Makefile.toml'
              - 'Cargo.lock'
              - '.github/workflows/**'
      - if: steps.changes.outputs.rust == 'true'
        uses: davidB/rust-cargo-make@v1
      - run: sudo apt-get install libmysqlclient-dev
      - if: steps.changes.outputs.rust == 'true'
        run: cargo make test-rust
